name: ct213exame
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.1.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - cachetools=4.2.2
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.5.2
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gymnasium=0.26.3
  - gymnasium-notices=0.0.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.2.2
  - openssl=3.0.9
  - opt_einsum=3.3.0
  - packaging=23.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.1.2
  - ply=3.11
  - pooch=1.4.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.29.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.10.1
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - tensorflow-gpu=2.4.1
  - termcolor=2.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=1.26.16
  - werkzeug=2.2.3
  - wheel=0.38.4
  - wrapt=1.14.1
  - xz=5.4.2
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
